cycle: 500ms
logging:
  level: info
  format: text
dsl:
  allow_if_blocks: true
helpers:
  - name: water_viscosity
    arguments: [temperature_c]
    expression: |
      if temperature_c < 0 {
        fail("helper.temperature", "below freezing")
      } else if temperature_c > 100 {
        fail("helper.temperature", "too hot")
      } else {
        temperature_c * 0.001
      }
cells:
  - id: raw_temperature
    type: number
    unit: counts
  - id: temperature_c
    type: number
    unit: "°C"
  - id: heater_enabled
    type: bool
  - id: heater_command
    type: bool
reads:
  - id: temperature_sensor
    endpoint:
      address: "192.168.10.10:502"
      unit_id: 1
    function: holding
    start: 0
    length: 1
    ttl: 1s
    signals:
      - cell: raw_temperature
        offset: 0
        type: number
        scale: 0.1
writes:
  - id: heater_output
    cell: heater_command
    endpoint:
      address: "192.168.10.20:502"
      unit_id: 1
    function: coil
    address: 5
    rate_limit: 2s
    priority: 10
logic:
  - id: convert_temperature
    target: temperature_c
    normal: |
      success(value("raw_temperature"))
    fallback: |
      success(0)
  - id: heater_control
    target: heater_command
    normal: |
      success(if value("heater_enabled") {
        fallback()
      } else if value("temperature_c") < 18 {
        true
      } else if value("temperature_c") > 21 {
        false
      } else {
        fallback()
      })
    fallback: |
      success(valid("temperature_c") ? false : fail("logic.dependency", "temperature unavailable"))
server:
  enabled: true
  listen: ":15020"
  unit_id: 1
  cells:
    - cell: temperature_c
      address: 0
      scale: 0.1
    - cell: heater_enabled
      address: 1
